//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VroomInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID { get; set; }
        public Nullable<decimal> Quote { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<short> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string DUI { get; set; }
        public Nullable<short> Tickets { get; set; }
        public string InsuranceType { get; set; }
    }
}
